// Generated by Tools/make-host-project.py.
import AudioToolbox
import MyPlugInCore
import MyDelay

/// Principal class of the MyDelay extension (see Info.plist).
final class MyDelayExtensionViewController: MyFXExtensionViewController {
    override func makeAudioUnit(componentDescription: AudioComponentDescription) throws -> MyFXAudioUnit {
        try MyDelayAudioUnit(componentDescription: componentDescription)
    }
}
