// Generated by Tools/make-host-project.py.
import AudioToolbox
import MyPlugInCore
import MyMaximizer

/// Principal class of the MyMaximizer extension (see Info.plist).
final class MyMaximizerExtensionViewController: MyFXExtensionViewController {
    override func makeAudioUnit(componentDescription: AudioComponentDescription) throws -> MyFXAudioUnit {
        try MyMaximizerAudioUnit(componentDescription: componentDescription)
    }
}
