// Generated by Tools/make-host-project.py.
import AudioToolbox
import MyPlugInCore
import MyChannelStrip

/// Principal class of the MyChannelStrip extension (see Info.plist).
final class MyChannelStripExtensionViewController: MyFXExtensionViewController {
    override func makeAudioUnit(componentDescription: AudioComponentDescription) throws -> MyFXAudioUnit {
        try MyChannelStripAudioUnit(componentDescription: componentDescription)
    }
}
