// Generated by Tools/make-host-project.py.
import AudioToolbox
import MyPlugInCore
import MyReverb

/// Principal class of the MyReverb extension (see Info.plist).
final class MyReverbExtensionViewController: MyFXExtensionViewController {
    override func makeAudioUnit(componentDescription: AudioComponentDescription) throws -> MyFXAudioUnit {
        try MyReverbAudioUnit(componentDescription: componentDescription)
    }
}
