// Generated by Tools/make-host-project.py.
import AudioToolbox
import MyPlugInCore
import MyChorusPan

/// Principal class of the MyChorusPan extension (see Info.plist).
final class MyChorusPanExtensionViewController: MyFXExtensionViewController {
    override func makeAudioUnit(componentDescription: AudioComponentDescription) throws -> MyFXAudioUnit {
        try MyChorusPanAudioUnit(componentDescription: componentDescription)
    }
}
