#!/usr/bin/env python3
"""Writes Hosts/MyPlugInHost: one AUv3 extension per effect in Package.swift
(`plugIns`), and MyPlugInHost.xcodeproj with the container app MyPlugIn.app.

    Tools/make-host-project.py

Run it after adding an effect. Extensions/<Name>/ files and the project are
generated: edit this script, not them. HostApp/ and Extension.entitlements
are kept as they are.
"""

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOST = ROOT / "Hosts" / "MyPlugInHost"
TEAM = "7LUU4H2M28"
BUNDLE_PREFIX = "com.tokada.MyPlugIn"
DEPLOYMENT_TARGET = "13.0"


def plug_ins():
    text = (ROOT / "Package.swift").read_text()
    block = re.search(r"let plugIns = \[(.*?)\]", text, re.S).group(1)
    return re.findall(r'"(My\w+)"', block)


def component(name):
    """(subtype, version) from Sources/<Name>/<Name>AudioUnit.swift."""
    text = (ROOT / "Sources" / name / f"{name}AudioUnit.swift").read_text()
    subtype = re.search(r'componentSubType: MyFXFourCC\("(.{4})"\)', text).group(1)
    version = re.search(r"class var version: UInt32 \{ (0x[0-9A-Fa-f_]+) \}", text)
    return subtype, int(version.group(1).replace("_", ""), 16) if version else 0x10000


def ident(*parts):
    return hashlib.md5("/".join(parts).encode()).hexdigest()[:24].upper()


def write_extension(name, subtype, version):
    folder = HOST / "Extensions" / name
    folder.mkdir(parents=True, exist_ok=True)
    (folder / f"{name}Extension.swift").write_text(f"""// Generated by Tools/make-host-project.py.
import AudioToolbox
import MyPlugInCore
import {name}

/// Principal class of the {name} extension (see Info.plist).
final class {name}ExtensionViewController: MyFXExtensionViewController {{
    override func makeAudioUnit(componentDescription: AudioComponentDescription) throws -> MyFXAudioUnit {{
        try {name}AudioUnit(componentDescription: componentDescription)
    }}
}}
""")
    (folder / "Info.plist").write_text(f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by Tools/make-host-project.py. -->
<plist version="1.0">
<dict>
	<key>CFBundleDisplayName</key>
	<string>{name}</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>XPC!</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.AudioUnit-UI</string>
		<key>NSExtensionPrincipalClass</key>
		<string>$(PRODUCT_MODULE_NAME).{name}ExtensionViewController</string>
		<key>NSExtensionAttributes</key>
		<dict>
			<key>AudioComponents</key>
			<array>
				<dict>
					<key>name</key>
					<string>Toka: {name}</string>
					<key>description</key>
					<string>{name}</string>
					<key>manufacturer</key>
					<string>Toka</string>
					<key>type</key>
					<string>aufx</string>
					<key>subtype</key>
					<string>{subtype}</string>
					<key>version</key>
					<integer>{version}</integer>
					<key>sandboxSafe</key>
					<true/>
					<key>tags</key>
					<array>
						<string>Effects</string>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
""")


def build_settings(settings):
    lines = "".join(f"\t\t\t\t{key} = {value};\n" for key, value in sorted(settings.items()))
    return "{\n" + lines + "\t\t\t}"


def project(names):
    objects = []

    def add(object_id, comment, body):
        objects.append((object_id, comment, body))

    package = ident("package")
    add(package, 'XCLocalSwiftPackageReference "../.."',
        "{\n\t\t\tisa = XCLocalSwiftPackageReference;\n\t\t\trelativePath = ../..;\n\t\t}")

    def product_dependency(target, product):
        dependency = ident("dependency", target, product)
        add(dependency, product,
            f"{{\n\t\t\tisa = XCSwiftPackageProductDependency;\n\t\t\tpackage = {package};\n"
            f"\t\t\tproductName = {product};\n\t\t}}")
        build_file = ident("buildfile", target, product)
        add(build_file, f"{product} in Frameworks",
            f"{{isa = PBXBuildFile; productRef = {dependency}; }}")
        return dependency, build_file

    def file_reference(path, file_type, name=None):
        reference = ident("file", path)
        label = name or Path(path).name
        add(reference, label,
            f'{{isa = PBXFileReference; lastKnownFileType = {file_type}; path = "{Path(path).name}"; '
            f'sourceTree = "<group>"; }}')
        return reference

    def phase(isa, key, files, extra=""):
        phase_id = ident("phase", key)
        listing = "".join(f"\t\t\t\t{f},\n" for f in files)
        add(phase_id, key, f"{{\n\t\t\tisa = {isa};\n\t\t\tbuildActionMask = 2147483647;\n{extra}"
                           f"\t\t\tfiles = (\n{listing}\t\t\t);\n\t\t\trunOnlyForDeploymentPostprocessing = 0;\n\t\t}}")
        return phase_id

    def configurations(key, settings):
        ids = []
        for configuration in ("Debug", "Release"):
            config_id = ident("config", key, configuration)
            add(config_id, configuration,
                f"{{\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbuildSettings = {build_settings(settings)};\n"
                f"\t\t\tname = {configuration};\n\t\t}}")
            ids.append(config_id)
        list_id = ident("configlist", key)
        listing = "".join(f"\t\t\t\t{i},\n" for i in ids)
        add(list_id, f"Build configuration list for {key}",
            f"{{\n\t\t\tisa = XCConfigurationList;\n\t\t\tbuildConfigurations = (\n{listing}\t\t\t);\n"
            f"\t\t\tdefaultConfigurationIsVisible = 0;\n\t\t\tdefaultConfigurationName = Release;\n\t\t}}")
        return list_id

    common = {
        "CODE_SIGN_STYLE": "Automatic",
        "DEVELOPMENT_TEAM": TEAM,
        "MACOSX_DEPLOYMENT_TARGET": DEPLOYMENT_TARGET,
        "PRODUCT_NAME": '"$(TARGET_NAME)"',
        "SDKROOT": "macosx",
        "SWIFT_VERSION": "5.0",
    }

    entitlements = file_reference("Extensions/Extension.entitlements", "text.plist.entitlements")
    extension_groups = []
    extension_targets = []
    embed_files = []
    extension_products = []
    for name in names:
        source = file_reference(f"Extensions/{name}/{name}Extension.swift", "sourcecode.swift")
        plist = file_reference(f"Extensions/{name}/Info.plist", "text.plist.xml")
        group = ident("group", name)
        add(group, name, f'{{\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = (\n\t\t\t\t{source},\n\t\t\t\t{plist},\n'
                         f'\t\t\t);\n\t\t\tpath = {name};\n\t\t\tsourceTree = "<group>";\n\t\t}}')
        extension_groups.append(group)

        target_name = f"{name}Extension"
        product = ident("product", target_name)
        add(product, f"{target_name}.appex",
            f'{{isa = PBXFileReference; explicitFileType = "wrapper.app-extension"; includeInIndex = 0; '
            f'path = {target_name}.appex; sourceTree = BUILT_PRODUCTS_DIR; }}')
        extension_products.append(product)
        source_build = ident("buildfile", target_name, "source")
        add(source_build, f"{name}Extension.swift in Sources", f"{{isa = PBXBuildFile; fileRef = {source}; }}")
        dependencies = [product_dependency(target_name, p) for p in ("MyPlugInCore", name)]
        sources = phase("PBXSourcesBuildPhase", f"{target_name} Sources", [source_build])
        frameworks = phase("PBXFrameworksBuildPhase", f"{target_name} Frameworks", [b for _, b in dependencies])
        settings = dict(common)
        settings.update({
            "APPLICATION_EXTENSION_API_ONLY": "YES",
            "CODE_SIGN_ENTITLEMENTS": "Extensions/Extension.entitlements",
            "INFOPLIST_FILE": f'"Extensions/{name}/Info.plist"',
            "PRODUCT_BUNDLE_IDENTIFIER": f"{BUNDLE_PREFIX}.{name}",
            "SKIP_INSTALL": "YES",
        })
        config_list = configurations(target_name, settings)
        target = ident("target", target_name)
        package_list = "".join(f"\t\t\t\t{d},\n" for d, _ in dependencies)
        add(target, target_name,
            f"{{\n\t\t\tisa = PBXNativeTarget;\n\t\t\tbuildConfigurationList = {config_list};\n"
            f"\t\t\tbuildPhases = (\n\t\t\t\t{sources},\n\t\t\t\t{frameworks},\n\t\t\t);\n"
            f"\t\t\tbuildRules = (\n\t\t\t);\n\t\t\tdependencies = (\n\t\t\t);\n\t\t\tname = {target_name};\n"
            f"\t\t\tpackageProductDependencies = (\n{package_list}\t\t\t);\n"
            f"\t\t\tproductName = {target_name};\n\t\t\tproductReference = {product};\n"
            f'\t\t\tproductType = "com.apple.product-type.app-extension";\n\t\t}}')
        extension_targets.append((target, target_name))
        embed = ident("buildfile", target_name, "embed")
        add(embed, f"{target_name}.appex in Embed Foundation Extensions",
            f"{{isa = PBXBuildFile; fileRef = {product}; settings = {{ATTRIBUTES = (RemoveHeadersOnCopy, ); }}; }}")
        embed_files.append(embed)

    # Container app.
    app_source = file_reference("HostApp/MyPlugInApp.swift", "sourcecode.swift")
    app_plist = file_reference("HostApp/Info.plist", "text.plist.xml")
    app_product = ident("product", "MyPlugIn")
    add(app_product, "MyPlugIn.app",
        "{isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; "
        "path = MyPlugIn.app; sourceTree = BUILT_PRODUCTS_DIR; }")
    app_source_build = ident("buildfile", "MyPlugIn", "source")
    add(app_source_build, "MyPlugInApp.swift in Sources", f"{{isa = PBXBuildFile; fileRef = {app_source}; }}")
    app_dependencies = [product_dependency("MyPlugIn", p) for p in ("MyPlugInCore", "MyPlugInCatalog")]
    app_sources = phase("PBXSourcesBuildPhase", "MyPlugIn Sources", [app_source_build])
    app_frameworks = phase("PBXFrameworksBuildPhase", "MyPlugIn Frameworks", [b for _, b in app_dependencies])
    app_embed = phase("PBXCopyFilesBuildPhase", "Embed Foundation Extensions", embed_files,
                      '\t\t\tdstPath = "";\n\t\t\tdstSubfolderSpec = 13;\n\t\t\tname = "Embed Foundation Extensions";\n')
    target_dependencies = []
    project_id = ident("project")
    for target, target_name in extension_targets:
        proxy = ident("proxy", target_name)
        add(proxy, "PBXContainerItemProxy",
            f"{{\n\t\t\tisa = PBXContainerItemProxy;\n\t\t\tcontainerPortal = {project_id};\n\t\t\tproxyType = 1;\n"
            f"\t\t\tremoteGlobalIDString = {target};\n\t\t\tremoteInfo = {target_name};\n\t\t}}")
        dependency = ident("targetdependency", target_name)
        add(dependency, "PBXTargetDependency",
            f"{{\n\t\t\tisa = PBXTargetDependency;\n\t\t\ttarget = {target};\n\t\t\ttargetProxy = {proxy};\n\t\t}}")
        target_dependencies.append(dependency)
    app_settings = dict(common)
    app_settings.update({
        "INFOPLIST_FILE": "HostApp/Info.plist",
        "PRODUCT_BUNDLE_IDENTIFIER": BUNDLE_PREFIX,
        "PRODUCT_NAME": "MyPlugIn",
    })
    app_config_list = configurations("MyPlugIn", app_settings)
    app_target = ident("target", "MyPlugIn")
    dependency_list = "".join(f"\t\t\t\t{d},\n" for d in target_dependencies)
    package_list = "".join(f"\t\t\t\t{d},\n" for d, _ in app_dependencies)
    add(app_target, "MyPlugIn",
        f"{{\n\t\t\tisa = PBXNativeTarget;\n\t\t\tbuildConfigurationList = {app_config_list};\n"
        f"\t\t\tbuildPhases = (\n\t\t\t\t{app_sources},\n\t\t\t\t{app_frameworks},\n\t\t\t\t{app_embed},\n\t\t\t);\n"
        f"\t\t\tbuildRules = (\n\t\t\t);\n\t\t\tdependencies = (\n{dependency_list}\t\t\t);\n\t\t\tname = MyPlugIn;\n"
        f"\t\t\tpackageProductDependencies = (\n{package_list}\t\t\t);\n"
        f"\t\t\tproductName = MyPlugIn;\n\t\t\tproductReference = {app_product};\n"
        f'\t\t\tproductType = "com.apple.product-type.application";\n\t\t}}')

    # Groups and project.
    host_app_group = ident("group", "HostApp")
    add(host_app_group, "HostApp", f'{{\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = (\n\t\t\t\t{app_source},\n'
                                   f'\t\t\t\t{app_plist},\n\t\t\t);\n\t\t\tpath = HostApp;\n\t\t\tsourceTree = "<group>";\n\t\t}}')
    extensions_group = ident("group", "Extensions")
    children = "".join(f"\t\t\t\t{g},\n" for g in [entitlements] + extension_groups)
    add(extensions_group, "Extensions", f'{{\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = (\n{children}\t\t\t);\n'
                                        f'\t\t\tpath = Extensions;\n\t\t\tsourceTree = "<group>";\n\t\t}}')
    products_group = ident("group", "Products")
    children = "".join(f"\t\t\t\t{p},\n" for p in [app_product] + extension_products)
    add(products_group, "Products", f'{{\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = (\n{children}\t\t\t);\n'
                                    f'\t\t\tname = Products;\n\t\t\tsourceTree = "<group>";\n\t\t}}')
    main_group = ident("group", "main")
    add(main_group, "main", f'{{\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = (\n\t\t\t\t{host_app_group},\n'
                            f'\t\t\t\t{extensions_group},\n\t\t\t\t{products_group},\n\t\t\t);\n'
                            f'\t\t\tsourceTree = "<group>";\n\t\t}}')
    project_config_list = configurations("project", {"ALWAYS_SEARCH_USER_PATHS": "NO"})
    targets = "".join(f"\t\t\t\t{t},\n" for t in [app_target] + [t for t, _ in extension_targets])
    add(project_id, "Project object",
        f"{{\n\t\t\tisa = PBXProject;\n\t\t\tattributes = {{\n\t\t\t\tLastUpgradeCheck = 2700;\n\t\t\t}};\n"
        f"\t\t\tbuildConfigurationList = {project_config_list};\n\t\t\tcompatibilityVersion = \"Xcode 15.0\";\n"
        f"\t\t\tdevelopmentRegion = en;\n\t\t\thasScannedForEncodings = 0;\n\t\t\tknownRegions = (\n\t\t\t\ten,\n\t\t\t);\n"
        f"\t\t\tmainGroup = {main_group};\n\t\t\tpackageReferences = (\n\t\t\t\t{package},\n\t\t\t);\n"
        f"\t\t\tproductRefGroup = {products_group};\n\t\t\tprojectDirPath = \"\";\n\t\t\tprojectRoot = \"\";\n"
        f"\t\t\ttargets = (\n{targets}\t\t\t);\n\t\t}}")

    body = "".join(f"\t\t{i} /* {c} */ = {b};\n" for i, c, b in sorted(objects))
    return ("// !$*UTF8*$!\n// Generated by Tools/make-host-project.py.\n{\n\tarchiveVersion = 1;\n\tclasses = {\n\t};\n"
            f"\tobjectVersion = 60;\n\tobjects = {{\n{body}\t}};\n\trootObject = {project_id};\n}}\n")


def main():
    names = plug_ins()
    for name in names:
        write_extension(name, *component(name))
    # Extensions of effects that are gone.
    for folder in (HOST / "Extensions").iterdir():
        if folder.is_dir() and folder.name not in names:
            for file in folder.iterdir():
                file.unlink()
            folder.rmdir()
    project_folder = HOST / "MyPlugInHost.xcodeproj"
    project_folder.mkdir(parents=True, exist_ok=True)
    (project_folder / "project.pbxproj").write_text(project(names))
    print(f"Wrote {project_folder.relative_to(ROOT)} with extensions: {', '.join(names)}")


if __name__ == "__main__":
    main()
